@api = http://192.168.1.1:5000/api/countries

### GET ALL
GET {{api}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkwNTQ3NDg1LCJleHAiOjE2OTA2MzM4ODV9.1PC8HSoraAtccAkqywXnFEspDKJb9yOioR5UqwYhksI

###
GET {{api}}/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg5NDI1NDMwLCJleHAiOjE2ODk1MTE4MzB9.MGgxEmiiewLVo0h_UbYfiJsGZ3QkIX_tsHKrx4rrBsc

###
POST {{api}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkwNTQ3NDg1LCJleHAiOjE2OTA2MzM4ODV9.1PC8HSoraAtccAkqywXnFEspDKJb9yOioR5UqwYhksI

{
    "name": "Colombia",
    "country_code": "57"
}

### UPDATE BY ID
PATCH {{api}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg5NDI1NDMwLCJleHAiOjE2ODk1MTE4MzB9.MGgxEmiiewLVo0h_UbYfiJsGZ3QkIX_tsHKrx4rrBsc

{
    "name": "Sebas updatee",
    "email": "sebas@gmail.com",
    "password": "qaws12pj-22",
    "connected": true
}

### DELETE
DELETE {{api}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg5NDI1NDMwLCJleHAiOjE2ODk1MTE4MzB9.MGgxEmiiewLVo0h_UbYfiJsGZ3QkIX_tsHKrx4rrBsc

