@api = http://192.168.1.1:5000/api/surveys

### GET ALL
GET {{api}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkwNTkxNTMxLCJleHAiOjE2OTA2Nzc5MzF9.MbCfplzStPaYhXOc8JYyaCZ0eEYtn-C9fcOKNgRg2Js

### CREATE
POST {{api}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg5NDI1NDMwLCJleHAiOjE2ODk1MTE4MzB9.MGgxEmiiewLVo0h_UbYfiJsGZ3QkIX_tsHKrx4rrBsc

{
    "code": "encuesta",
    "txtWelcome": "Bienvenidos soy Sebas, votarias por mi?",
    "txtYes": "Gracias, txt Yes",
    "txtNo": "Gracias, txt No",
    "info": {
        "nombre":"ingresa tu nombre",
        "cedula":"ingresa tu numero de cedula"
    },
}

### GET BY ID
GET {{api}}/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg5NDI1NDMwLCJleHAiOjE2ODk1MTE4MzB9.MGgxEmiiewLVo0h_UbYfiJsGZ3QkIX_tsHKrx4rrBsc

### UPDATE BY ID
PATCH {{api}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg5NDI1NDMwLCJleHAiOjE2ODk1MTE4MzB9.MGgxEmiiewLVo0h_UbYfiJsGZ3QkIX_tsHKrx4rrBsc

{
    "code": "encuesta",
    "txtWelcome": "Bienvenidos soy Sebas, votarias por mi?",
    "txtYes": "Gracias, txt Yes",
    "txtNo": "Gracias, txt No",
    "info": {
        "nombre":"ingresa tu nombre",
        "cedula":"ingresa tu numero de cedula"
    },
}

### DELETE
DELETE {{api}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg5NDI1NDMwLCJleHAiOjE2ODk1MTE4MzB9.MGgxEmiiewLVo0h_UbYfiJsGZ3QkIX_tsHKrx4rrBsc

